### ISSUE TITLE
Text entry requiring correct capitalization

### ISSUE THREAD

**Issue by coolspee** [LYE-Software/Lang#14]
On Quizlet correct capitalization is not required on text entry questions. Would it be possible to add a feature like this to Lang?
 
![image](https://github.com/LYE-Software/Lang/assets/79561546/7575be7f-a112-4455-bc00-8750238feb6d)

**Comment by coolspee** [comment]
I'll try to find a fix

**Comment by nwvbug** [comment]
Thank you for bringing this to my attention. However, I would just like to say that at the moment Lang is not accepting contributions, although we really do appreciate what you are doing. It would be complicated at the moment to have more people working on the project, so we will fix the issue. We really appreciate your interest in Lang and would love if you continued documenting your errors, however.

**Comment by nwvbug** [comment]
Fixed
