### ISSUE TITLE
New homepage looks bad

### ISSUE THREAD

**Issue by ankleBowl** [LYE-Software/Lang#6]
it should be merged with the internal devlopmemt version

**Comment by nwvbug** [comment]
why

**Comment by nwvbug** [comment]
<div class="tenor-gif-embed" data-postid="20797837" data-share-method="host" data-aspect-ratio="0.84375" data-width="100%"><a href="https://tenor.com/view/cope-cope-harder-coping-lol-cope-harder-fortnite-gif-20797837">Cope Cope Harder Sticker</a>from <a href="https://tenor.com/search/cope-stickers">Cope Stickers</a></div> <script type="text/javascript" async src="https://tenor.com/embed.js"></script>
